name: Prefix-Based Branch Creation

on:
  push:
    branches:
      - main

jobs:
  cherry-pick-and-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git user
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Fetch all branches
        run: |
          git fetch --all

      - name: Filter and Cherry-Pick Commits
        env:
          REPO_URL: "https://github.com/mukuldualite/Amartesh.git"
          TOKEN: ${{ secrets.GI_TOKEN }}
        run: |
          # Define prefixes and corresponding branch names
          prefixes=("fixed" "polished" "ready" "misc" "generated")
          for prefix in "${prefixes[@]}"; do
            # Find commits with the prefix
            commits=$(git log --format='%H %s' main | grep -E "^$prefix:" | awk '{print $1}')
            if [[ -n "$commits" ]]; then
              branch="${prefix}-branch"
              
              # Check if the branch exists, if not, create it from main
              if ! git show-ref --quiet refs/heads/"$branch"; then
                git checkout -b "$branch" origin/main
              else
                git checkout "$branch"
                git merge origin/main
              fi
              
              # Cherry-pick commits
              for commit in $commits; do
                git cherry-pick "$commit" || (echo "Cherry-pick failed for commit $commit" && git cherry-pick --abort && exit 1)
              done
              
              # Push to the branch on GitHub using the PAT
              git push https://${{secrets.GI_TOKEN }}@github.com/mukuldualite/Amartesh.git "$branch"
            fi
          done
      - name: Push changes
        env:
          REPO_URL: "https://github.com/mukuldualite/Amartesh.git"
          TOKEN: ${{ secrets.GI_TOKEN }}
        run: |
             git remote set-url origin https://${{ secrets.GI_TOKEN }}@github.com/mukuldualite/Amartesh.git
             git push origin --all
